config/routes.rb
Rails.application.routes.draw do

  get 'cars/:car_id/likes' => 'likes#create'
  get 'cars/:car_id/likes/:id' => 'likes#destroy'
  post 'cars/basic' => 'cars#basic'
  post 'cars/middle' => 'cars#middle'
  post 'cars/premium' => 'cars#premium'
  get 'cars/hajimari' => 'cars#hajimari'

  devise_for :users
  resources :users, only: [:show]
  resources :carpicks
  get 'carpicks/note' => 'carpicks#note'

  resources :cars do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'cars#index' #localhost:3000の時indexページに飛ぶ！
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

end

app/models/carpick.rb
class Carpick < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :car
  belongs_to :user
  
  validates_uniqueness_of :car_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cars, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
         has_many :likes, dependent: :destroy
         has_many :liked_cars, through: :likes, source: :car
         has_many :comments, dependent: :destroy
        def already_liked?(car)
          self.likes.exists?(car_id: car.id)
        end
         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end

end

app/controllers/carpicks_controller.rb
class CarpicksController < ApplicationController
    def index
    end

    def note
    end

    def new
        @carpick = Carpick.new
    end

    def show
        @carpick = Carpick.find_by(id: params[:id])
    end


    def create
        carpick = Carpick.new(carpick_params)
        if carpick.save
            flash[:notice] = "診断が完了しました"
            redirect_to carpick_path(carpick.id)
        else
            redirect_to :action => "new"
        end
    end
  
  private
    def carpick_params
        params.require(:carpick).permit(:question1, :question2, :question3)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

    def index
        @cars = Car.all
    end  

    before_action :authenticate_user!, only: [:new, :create]

    def new
      @car = Car.new
    end
      
    def create
          car = Car.new(car_params)
          car.user_id = current_user.id
          if car.save!
            redirect_to :action => "index"
          else
            redirect_to :action => "new"
          end
    end

    def show
      @car = Car.find(params[:id])
    end

    def destroy
      car = Car.find(params[:id])
      car.destroy
      redirect_to action: :index
    end

    def show
      @car = Car.find(params[:id])
      @comments = @car.comments
      @comment = Comment.new
    end

    def edit
      @car = Car.find(params[:id])
    end

    def update
      car = Car.find(params[:id])
      if car.update(car_params)
        redirect_to :action => "show", :id => car.id
      else
        redirect_to :action => "new"
      end
    end

    def hajimari
      @cars = Car.all
    end

    def basic
      @cars = Car.all
    end
  
    def middle
      @cars = Car.all
    end
  
    def premium
      @cars = Car.all
    end

        private
        def car_params
        params.require(:car).permit(:name, :grade, :capacity, :image, :category, :body, :hoshihyouka, :comfort, :ease_of_driving, :shashu)
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    class CommentsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          car = Car.find(params[:car_id])
          comment = car.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
          comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          end
        end
      
        private
      
          def comment_params
            params.require(:comment).permit(:content)
          end
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(car_id: params[:car_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(car_id: params[:car_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carpicks_helper.rb
module CarpicksHelper
end

app/helpers/cars_helper.rb
module CarsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carpicks/index.html.erb
<div class="shindan">
    <h1>車種診断スタート</h1>
    <%= link_to "診断を始める", new_carpick_path, class: "link" %>
</div>

app/views/carpicks/note.html.erb
ノート詳細

app/views/cars/basic.html.erb
<h1 id="sainappu">ベーシッククラス一覧</h1>
<div class="tweets-container">
    <% @cars.each do |t| %>
      <% if t.category == "basic" %>  
        <div class="tweet">
          <div class="c-image-premium">
              <%= image_tag t.image_url, size: "250x160" if t.image? %>
          </div>
          <%= t.name %>
          <%= t.grade %>
          <%= t.capacity %>
          <%= link_to "詳細へ", car_path(t.id) %>
          <%= link_to "一覧へ", cars_hajimari_path %> 
      </div>
    <% end %>
  <% end %>
</div>

app/views/cars/edit.html.erb
<div class="new-post-form">
  <%= form_for @car do |f| %>

    <!-- 名前フィールド -->
    <div class="field">
      <%= f.label :名前 %>
      <%= f.text_field :name, :size => 30 %>
    </div>

    <!-- 車種フィールド -->
    <div class="field">
      <%= f.label :車種  %>
      <%= f.text_field :shashu, :size => 30 %>
    </div>

    <!-- 感想フィールド -->
    <div class="field">
      <%= f.label :感想  %>
      <%= f.text_field :body, :size => 80 %>
    </div>

    <!-- 画像アップロードフィールド -->
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    
    <!-- 総合評価 -->
    <h5>総合評価</h5>
    <div class="post_form">
       <%= f.radio_button :hoshihyouka, 5 ,id: 'star1'%>
       <label for="star1"><span class="text">最高</span>★</label>

       <%= f.radio_button :hoshihyouka, 4 ,id: 'star2'%>
       <label for="star2"><span class="text">良い</span>★</label>

       <%= f.radio_button :hoshihyouka, 3 ,id: 'star3'%>
       <label for="star3"><span class="text">普通</span>★</label>

       <%= f.radio_button :hoshihyouka, 2 ,id: 'star4'%>
       <label for="star4"><span class="text">悪い</span>★</label>

       <%= f.radio_button :hoshihyouka, 1 ,id: 'star5'%>
       <label for="star5"><span class="text">最悪</span>★</label>
    </div>

    <!-- 快適さ -->
    <h5>快適さ、スピーカーの音質など</h5>
    <div class="post_form">
      <%= f.radio_button :comfort,  5 ,id: 'star6'%>
      <label for="star6"><span class="text">めちゃくちゃいい</span>★</label>

      <%= f.radio_button :comfort,  4 ,id: 'star7'%>
      <label for="star7"><span class="text">良い</span>★</label>

      <%= f.radio_button :comfort, 3 ,id: 'star8'%>
      <label for="star8"><span class="text">普通</span>★</label>

      <%= f.radio_button :comfort , 2 ,id: 'star9'%>
      <label for="star9"><span class="text">ちょっと悪い</span>★</label>

      <%= f.radio_button :comfort , 1 ,id: 'star10'%>
      <label for="star10"><span class="text">悪い</span>★</label>
    </div>

    <!-- 運転のしやすさ -->
    <h5>運転のしやすさ</h5>
    <div class="post_form">
      <%= f.radio_button :ease_of_driving,  5 ,id: 'star11'%>
      <label for="star11"><span class="text">簡単</span>★</label>

      <%= f.radio_button :ease_of_driving,  4 ,id: 'star12'%>
      <label for="star12"><span class="text">やや簡単</span>★</label>

      <%= f.radio_button :ease_of_driving, 3 ,id: 'star13'%>
      <label for="star13"><span class="text">普通</span>★</label>

      <%= f.radio_button :ease_of_driving, 2 ,id: 'star14'%>
      <label for="star14"><span class="text">やや難しい</span>★</label>

      <%= f.radio_button :ease_of_driving, 1 ,id: 'star15'%>
      <label for="star15"><span class="text">難しい</span>★</label>
    </div>

    <!-- クラス選択 -->
    <div class="field">
      <%= f.select :category, [["basic"], ["middle"], ["premium"]], include_blank: "どのクラス？" %>
    </div>

    <!-- 投稿ボタン -->
    <div class="actions">
      <%= f.submit "投稿する" %>
    </div>

  <% end %>

  <%= link_to "一覧に戻る", cars_path, class: 'back-link' %>
</div>

app/views/cars/hajimari.html.erb
<body>
    <div class="button-container">
      <div class="button-basic">
        <%= button_to "ベーシック", cars_basic_path %>
      </div>
      <div class="button-basic">
        <%= button_to "ミドル", cars_middle_path %>
      </div>
      <div class="button-basic">
        <%= button_to "プレミアム", cars_premium_path %>
      </div>
    </div>
</body>

<h1 id="sainappu">投稿一覧</h1>
<%= link_to "新規投稿へ", new_car_path %>
<div class="tweets-container">
  <% @cars.each do |t| %>
    <div class="tweet">
      <div class="c-image">
          <%= image_tag t.image_url, size: "250x160" if t.image? %>
      </div>
      <%= t.name %>
      <%= t.grade %>
      <%= t.capacity %>
      <%= link_to "詳細へ", car_path(t.id) %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= link_to car_like_path(id: t.id, car_id: t.id), method: :delete do %>
            <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to car_likes_path(id: t.id, car_id: t.id), method: :post do %>
            <p>いいね</p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
      <% end %>


    </div>
  <% end %>
</div>

app/views/cars/index.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>緯線ボタンの例</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="button-container">
        <%= link_to "新規投稿へ", new_car_path %>
        <%= link_to "一覧へ", cars_hajimari_path %>
        <%= link_to "診断を始める", new_carpick_path, class: "link" %>
    </div>

    <div class="setumei-container">
      <p class="title">まずは診断してみよう！</p>
      <%= link_to "診断を始める", new_carpick_path, class: "link" %>
      <p class="description">利用した感想を車種とともに投稿しよう</p>
      <%= link_to "新規投稿へ", new_car_path %>
    </div>

    <!-- 新しく追加する料金情報のセクション -->
    <div class="pricing-container">
      <h2>料金プラン</h2>

      <div class="pricing-table">
        <div class="pricing-basic">
          <h3>ベーシック</h3>
          <p>平日料金（15分）: ¥220</p>
          <p>距離料金（1Km当たり）: ¥20</p>
          <p>6時間パック: ¥4,080</p>
        </div>

        <div class="pricing-middle">
          <h3>ミドル</h3>
          <p>平日料金（15分）: ¥270</p>
          <p>距離料金（1Km当たり）: ¥20</p>
          <p>6時間パック: ¥4,480</p>
        </div>

        <div class="pricing-premium">
          <h3>プレミアム</h3>
          <p>平日料金（15分）: ¥320</p>
          <p>距離料金（1Km当たり）: ¥20</p>
          <p>6時間パック: ¥5,480</p>
        </div>
      </div>
    </div>
</body>

app/views/cars/index2.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>緯線ボタンの例</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="button-container">
        <div class="button-basic">
            <%= button_to "ベーシック", cars_basic_path %>
        </div>
        <div class="button-basic">
            <%= button_to "ミドル", cars_middle_path %>
        </div>
        <div class="button-basic">
            <%= button_to "プレミアム", cars_premium_path %>
        </div>
        <%= link_to "新規投稿へ", new_car_path %>
        <%= link_to "一覧へ", cars_hajimari_path %>
        <%= link_to "診断を始める", new_carpick_path, class: "link" %>
    </div>

    <div>
      <div class="ryoukinn">
      
        <div class="ryoukinn-b">
        <p10>ベーシック<p10>
        </div>

        <div class="ryoukinn-m">
        <p10>ミドル<p10>
        </div>

        <div class="ryoukinn-p">
        <p10>プレミアム<p10>
        </div>

      </div>
    </div>
</body>




newのとこ
<div class="field">
<%= f.label :クラス  %>
<%= f.select :grade, 
[["basic", "basic"], 
["midle", "midle"], 
["premium", "premium"]], include_blank: "選択して下さい" %>
</div>

<div class="field">
<%= f.label :乗車人数  %>
<%= f.number_field :capacity, :size => 10 %>
</div>






<%= form_for @car do |f| %>

    <div class="field">
      <%= f.label :名前 %>
      <%= f.text_field :name, :size => 30 %>
    </div>
  
    <div class="field">
      <%= f.label :車種  %>
      <%= f.text_field :name, :size => 30 %>
    </div>
  
    <div class="field">
      <%= f.label :感想  %>
      <%= f.text_field :body, :size => 80%>
    </div>
  
    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    </div>
    <%= f.select :category, [["basic"], ["middle"], ["premium"]], include_blank: "どのクラス？" %>
    <%= f.submit "投稿する" %>
  <% end %>
  
  <%= link_to "一覧に戻る", cars_path %>

app/views/cars/middle.html.erb
<h1 id="sainappu">ミドルクラス一覧</h1>
<div class="container-premium">
    <% @cars.each do |t| %>
        <% if t.category == "middle" %>  
            <div class="tweet">
                <div class="c-image-premium">
                    <%= image_tag t.image_url, size: "250x200" if t.image? %>
                </div>
                <%= t.name %>
                <%= t.grade %>
                <%= t.capacity %>
                <%= link_to "詳細へ", car_path(t.id) %>
                <%= link_to "一覧へ", cars_hajimari_path %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/cars/new.html.erb
<h1 id="sainappu">使ってみた感想！</h1>
<h3 id="sainappu">新規投稿ページ</h3>

<%= form_for @car, html: { class: "new-post-form" } do |f| %>

  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name, size: 30 %>
  </div>

  <div class="field">
    <%= f.label :車種 %>
    <%= f.text_field :shashu, size: 30 %>
  </div>

  <div class="field">
    <%= f.label :感想 %>
    <%= f.text_area :body, size: "80x5" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <!-- ★評価機能のデザインはそのまま維持 -->
  <h5>総合評価</h5>
  <div class="post_form">
    <%= f.radio_button :hoshihyouka, 5, id: 'star1' %>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :hoshihyouka, 4, id: 'star2' %>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :hoshihyouka, 3, id: 'star3' %>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :hoshihyouka, 2, id: 'star4' %>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :hoshihyouka, 1, id: 'star5' %>
    <label for="star5"><span class="text">最悪</span>★</label>
  </div>

  <h5>快適さ、スピーカーの音質など</h5>
  <div class="post_form">
    <%= f.radio_button :comfort, 5, id: 'star6' %>
    <label for="star6"><span class="text">めちゃくちゃいい</span>★</label>

    <%= f.radio_button :comfort, 4, id: 'star7' %>
    <label for="star7"><span class="text">良い</span>★</label>

    <%= f.radio_button :comfort, 3, id: 'star8' %>
    <label for="star8"><span class="text">普通</span>★</label>

    <%= f.radio_button :comfort, 2, id: 'star9' %>
    <label for="star9"><span class="text">ちょっと悪い</span>★</label>

    <%= f.radio_button :comfort, 1, id: 'star10' %>
    <label for="star10"><span class="text">悪い</span>★</label>
  </div>

  <h5>運転のしやすさ</h5>
  <div class="post_form">
    <%= f.radio_button :ease_of_driving, 5, id: 'star11' %>
    <label for="star11"><span class="text">難しい</span>★</label>

    <%= f.radio_button :ease_of_driving, 4, id: 'star12' %>
    <label for="star12"><span class="text">やや難しい</span>★</label>

    <%= f.radio_button :ease_of_driving, 3, id: 'star13' %>
    <label for="star13"><span class="text">普通</span>★</label>

    <%= f.radio_button :ease_of_driving, 2, id: 'star14' %>
    <label for="star14"><span class="text">やや簡単</span>★</label>

    <%= f.radio_button :ease_of_driving, 1, id: 'star15' %>
    <label for="star15"><span class="text">簡単</span>★</label>
  </div>

  <%= f.select :category, [["basic"], ["middle"], ["premium"]], include_blank: "どのクラス？" %>
  <div class="actions">
    <%= f.submit "投稿する" %>
  </div>

<% end %>

<%= link_to "一覧に戻る", cars_path, class: 'back-link' %>

app/views/cars/premium.html.erb
<h1 id="sainappu">プレミアムクラス一覧</h1>
<div class="container-premium">
  <% @cars.each do |t| %>
    <% if t.category == "premium" %>  
      <div class="tweet">
        <div class="c-image-premium">
          <%= image_tag t.image_url, size: "250x200" if t.image? %>
        </div>
        <%= t.name %>
        <%= t.grade %>
        <%= t.capacity %>
        <%= link_to "詳細へ", car_path(t.id) %>
        <%= link_to "一覧へ", cars_hajimari_path %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="car-details">
  <div class="car-info">
    <p><strong>車の名前:</strong> <%= @car.name %></p>
    <p><strong>車種:</strong> <%= @car.shashu %></p>
    <p><strong>感想:</strong> <%= @car.body %></p>

    <p>
      <% if @car.image.present? %>
        <%= image_tag @car.image.url %>
      <% end %>
    </p>

    <!-- 投稿日時の表示 -->
    <p><strong>投稿日時:</strong> <%= @car.created_at.strftime("%Y-%m-%d %H:%M") %></p>

    <!-- 投稿者の表示 -->
    <p><strong>投稿者:</strong> <%= @car.user.email %></p>
  </div>

  <!-- 評価セクション -->
  <div class="rating-section">
    <h2>総合評価：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(@car.hoshihyouka) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span>
    </h2>
  </div>

  <div class="rating-section">
    <h2>快適さ、スピーカーの音質など：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(@car.comfort) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span>
    </h2>
  </div>

  <div class="rating-section">
    <h2>運転のしやすさ：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(@car.ease_of_driving) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span>
    </h2>
  </div>

  <!-- 編集・削除アクション -->
  <div class="car-actions">
    <%= link_to "編集する", edit_car_path(@car.id), class: "btn-edit" %>
    <%= button_to "削除する", car_path(@car.id), method: :delete, class: "btn-delete" %>
  </div>

  <!-- いいね機能 -->
  <div class="likes-section">
    <p>いいねの数：<%= @car.likes.count %></p>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(@car) %>
        <%= link_to "いいねを取り消す", car_like_path(@car), method: :delete %>
      <% else %>
        <%= link_to "いいね", car_likes_path(@car), method: :post %>
      <% end %>
    <% end %>
  </div>

  <!-- いいねしたユーザー -->
  <h2>いいねしたユーザー</h2>
  <ul>
    <% @car.liked_users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
  </ul>

  <!-- 戻るリンク -->
  <%= link_to "ホームに戻る", cars_path, class: "back-link" %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@car, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <h1>Carshare</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
      <%= link_to "マイページ", user_path(current_user.id) %>
      <%= link_to "ホーム", cars_path %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbolinks: false } %>
    <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
 <footer>
 <p>Copyright © GeekSalon All Rights Reserved.</p>
</footer>
</body>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>My page</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.cars.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
  <%= t.grade %>
  <%= t.capacity %>
  <%= t.image %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_cars.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
  <%= t.grade %>
  <%= t.capacity %>
  <%= t.image %>
<% end %>

<%= link_to "一覧に戻る", cars_path %>